package httpapi

import (
	"net/http"
	"net/http/httptest"
	"testing"
)

// Regression: if PromoAdminSecret is empty (env not set on the server), the HMAC
// signature returns an empty string, and promoAdminTokenValid must return false
// for ANY token (fail-closed). This is protective: we do not want anyone who
// knows a hard-coded fallback to get through.
// Real incident 2026-06-01: prod had no PROMO_ADMIN_SECRET in .env.prod
// → every created promo admin URL answered 'promo admin link is invalid'.

func TestPromoAdminToken_EmptySecretRejectsAllTokens(t *testing.T) {
	t.Parallel()

	h := Handler{PromoAdminSecret: ""}

	req := httptest.NewRequest(http.MethodGet, "/?key=anything&promo=TEST", nil)
	if h.promoAdminTokenValid(req, "TEST") {
		t.Errorf("empty secret should reject all tokens, but accepted")
	}

	req2 := httptest.NewRequest(http.MethodGet, "/?key=&promo=TEST", nil)
	if h.promoAdminTokenValid(req2, "TEST") {
		t.Errorf("empty key + empty secret accepted (must be rejected)")
	}
}

func TestPromoAdminToken_NonEmptySecretAcceptsMatchingToken(t *testing.T) {
	t.Parallel()

	h := Handler{PromoAdminSecret: "test-secret-must-be-set"}

	// Generate a valid token for code 'TEST' ourselves and check it is accepted.
	token := h.promoAdminToken("TEST")
	if token == "" {
		t.Fatal("token is empty even with secret set")
	}

	req := httptest.NewRequest(http.MethodGet, "/?key="+token+"&promo=TEST", nil)
	if !h.promoAdminTokenValid(req, "TEST") {
		t.Errorf("valid token rejected")
	}
}

func TestPromoAdminToken_WrongTokenRejected(t *testing.T) {
	t.Parallel()

	h := Handler{PromoAdminSecret: "test-secret-must-be-set"}
	req := httptest.NewRequest(http.MethodGet, "/?key=wrong-token&promo=TEST", nil)
	if h.promoAdminTokenValid(req, "TEST") {
		t.Errorf("wrong token accepted")
	}
}

func TestPromoAdminToken_DifferentSecretRejects(t *testing.T) {
	t.Parallel()

	// Simulate the scenario: a token generated by one server (secret A) is
	// validated by another (secret B). All links must be rejected.
	h1 := Handler{PromoAdminSecret: "secret-A"}
	h2 := Handler{PromoAdminSecret: "secret-B"}

	token := h1.promoAdminToken("TEST")
	req := httptest.NewRequest(http.MethodGet, "/?key="+token+"&promo=TEST", nil)
	if h2.promoAdminTokenValid(req, "TEST") {
		t.Errorf("token from different secret accepted")
	}
}

func TestPromoAdminToken_AcceptsTokenQueryParamAlias(t *testing.T) {
	t.Parallel()

	// Compatibility: the handler accepts both ?key= and ?token=.
	h := Handler{PromoAdminSecret: "secret"}
	token := h.promoAdminToken("TEST")

	req := httptest.NewRequest(http.MethodGet, "/?token="+token+"&promo=TEST", nil)
	if !h.promoAdminTokenValid(req, "TEST") {
		t.Errorf("token via ?token= alias rejected")
	}
}
